#!/usr/bin/env bash

#MISE description="Install node deps"

set -euo pipefail

echo "Downloading node deps..."

npm install -g corepack

corepack enable # allows to respect the packageManager field in the package.json automatically

cd gh/setup-action
yarn install
cd -

cd scripts/sync-example-confirmer-to-real-example
yarn install
cd -

cd gh/.almost-original-build-push-action
yarn install
cd -