# GoReleaser config for mimosa
project_name: mimosa
builds:
  - id: mimosa
    main: ./cmd/mimosa
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
archives:
  - id: default
    builds:
      - mimosa
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
release:
  github:
    owner: hytromo
    name: mimosa
