project_name: mimosa
builds:
  - id: mimosa
    main: ./cmd/mimosa
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
archives:
  - id: default
    ids:
      - mimosa
    formats: [ 'tar.gz' ]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
    owner: hytromo
    name: mimosa
