version: 2
project_name: mimosa

builds:
  - id: mimosa
    main: ./
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/hytromo/mimosa/cmd.Version={{ .Version }}
      - -X github.com/hytromo/mimosa/cmd.Commit={{ .ShortCommit }}
      - -X github.com/hytromo/mimosa/cmd.Date={{ .Date }}
    env:
      - CGO_ENABLED=0
archives:
  - id: default
    ids:
      - mimosa
    formats: [ 'tar.gz' ]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
    owner: hytromo
    name: mimosa
