#!/usr/bin/env bash

#MISE description="Initialize the tests"

set -euo pipefail

if ! docker buildx ls | grep mimosa-host-network-builder; then
  echo "Creating docker buildx builder with host network..."
  docker buildx create --use --name mimosa-host-network-builder --driver docker-container --driver-opt network=host --use
fi

docker buildx use mimosa-host-network-builder

CONTAINER_NAME="mimosa_registry"
if [ "$(docker ps -q -f name="$CONTAINER_NAME")" == "" ]; then
  echo "Starting local registry..."
  docker run -d -p 5000:5000 --name "$CONTAINER_NAME" --rm registry:3
else
  echo "Local registry already running."
fi