name: Mimosa GitHub Action Example

on:
  pull_request:

permissions:
  contents: write

jobs:
  example-github-action:
    name: "Registry-based caching example"
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup mimosa
        id: setup-mimosa
        uses: hytromo/mimosa/gh/setup-action@v2-setup
        with:
          version: v0.1.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::947281064882:role/mimosa-github-actions-role
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: hytromo
          password: ${{ secrets.DOCKER_PAT }}

      - name: Prepare build context
        working-directory: docs/gh-actions/actions-example
        run: |
          echo $RANDOM > to-ignore.txt
          echo "${{ github.sha }}-${RANDOM}-$(date)" > useful.txt

      - name: Build and push to Docker Hub
        id: build-dockerhub
        uses: hytromo/mimosa/gh/build-push-action@v6-build-push
        with:
          mimosa-setup-enabled: false
          context: docs/gh-actions/actions-example
          platforms: linux/amd64,linux/arm64
          push: true
          tags: hytromo/mimosa-testing:recommended-example-${{ github.sha }}

      - name: Build and push to ECR
        id: build-ecr
        uses: hytromo/mimosa/gh/build-push-action@v6-build-push
        with:
          mimosa-setup-enabled: false
          context: docs/gh-actions/actions-example
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/mimosa-testing:recommended-example-${{ github.sha }}

      ### That's it! - the next steps are just proving that the cache is working - you DO NOT need to include them in your typical workflow
      - name: Prepare build context for cache verification
        working-directory: docs/gh-actions/actions-example
        run: |
          # Change an ignored file - this should NOT affect the hash
          echo $RANDOM > to-ignore.txt

      - name: Build and push to Docker Hub (cache verification)
        id: build-dockerhub-cache-hit
        uses: hytromo/mimosa/gh/build-push-action@v6-build-push
        with:
          mimosa-setup-enabled: false
          context: docs/gh-actions/actions-example
          platforms: linux/amd64,linux/arm64
          push: true
          tags: hytromo/mimosa-testing:recommended-example-cache-hit-${{ github.sha }}

      - name: Build and push to ECR (cache verification)
        id: build-ecr-cache-hit
        uses: hytromo/mimosa/gh/build-push-action@v6-build-push
        with:
          mimosa-setup-enabled: false
          context: docs/gh-actions/actions-example
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/mimosa-testing:recommended-example-cache-hit-${{ github.sha }}

      - name: Verify cache hit outputs
        run: |
          errors=()
          [ "${{ steps.build-dockerhub.outputs.mimosa-cache-hit }}" = "false" ] || errors+=("ERROR: Initial Docker Hub build should have cache-hit=false")
          [ "${{ steps.build-ecr.outputs.mimosa-cache-hit }}" = "false" ] || errors+=("ERROR: Initial ECR build should have cache-hit=false")
          [ "${{ steps.build-dockerhub-cache-hit.outputs.mimosa-cache-hit }}" = "true" ] || errors+=("ERROR: Docker Hub cache verification should have cache-hit=true")
          [ "${{ steps.build-ecr-cache-hit.outputs.mimosa-cache-hit }}" = "true" ] || errors+=("ERROR: ECR cache verification should have cache-hit=true")
          if [ ${#errors[@]} -gt 0 ]; then
            printf '%s\n' "${errors[@]}"
            exit 1
          fi
          echo "All cache hit outputs verified successfully!"
