name: Cleanup GitHub Container Registry

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  packages: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete
        uses: actions/delete-package-versions@v5
        with:
          package-type: container
          package-name:  mimosa/mimosa-testing 
          min-versions-to-keep: 20
